## Read files

In [1]:
import cudf as gd

In [2]:
path = '/rapids/notebooks/srabhi/champs-2019/input/csv/'

In [24]:
%%time
train = gd.read_csv('%s/train.csv'%path)
test = gd.read_csv('%s/test.csv'%path)
print(train.shape,test.shape)
test['scalar_coupling_constant'] = 0.0 
for col in train.columns:
    if train[col].dtype!='O':
        train[col] = train[col].astype('float32')
        if col in test.columns:
            test[col] = test[col].astype('float32')
struct = gd.read_csv('%s/structures.csv'%path)
for col in struct.columns:
    if struct[col].dtype!='O':
        struct[col] = struct[col].astype('float32')
print(struct.shape)
contribs = gd.read_csv('%s/scalar_coupling_contributions.csv'%path)
for col in contribs.columns:
    if contribs[col].dtype!='O':
        contribs[col] = contribs[col].astype('float32')
print(contribs.shape)

(4658147, 6) (2505542, 5)
(2358657, 6)
(4658147, 8)
CPU times: user 784 ms, sys: 460 ms, total: 1.24 s
Wall time: 2.57 s

In [25]:
contribs.head().to_pandas()

,molecule_name,atom_index_0,atom_index_1,type,fc,sd,pso,dso
0,dsgdb9nsd_000001,1.0,0.0,1JHC,83.022400,0.254579,1.25862,0.272010
1,dsgdb9nsd_000001,1.0,2.0,2JHH,-11.034700,0.352978,2.85839,-3.433600
2,dsgdb9nsd_000001,1.0,3.0,2JHH,-11.032500,0.352944,2.85852,-3.433870
3,dsgdb9nsd_000001,1.0,4.0,2JHH,-11.031900,0.352934,2.85855,-3.433930
4,dsgdb9nsd_000001,2.0,0.0,1JHC,83.022202,0.254585,1.25861,0.272013

In [26]:
train.head().to_pandas()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
0,0.0,dsgdb9nsd_000001,1.0,0.0,1JHC,84.807602
1,1.0,dsgdb9nsd_000001,1.0,2.0,2JHH,-11.257000
2,2.0,dsgdb9nsd_000001,1.0,3.0,2JHH,-11.254800
3,3.0,dsgdb9nsd_000001,1.0,4.0,2JHH,-11.254300
4,4.0,dsgdb9nsd_000001,2.0,0.0,1JHC,84.807404

In [27]:
test.head().to_pandas()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
0,4658147.0,dsgdb9nsd_000004,2.0,0.0,2JHC,0.0
1,4658148.0,dsgdb9nsd_000004,2.0,1.0,1JHC,0.0
2,4658149.0,dsgdb9nsd_000004,2.0,3.0,3JHH,0.0
3,4658150.0,dsgdb9nsd_000004,3.0,0.0,1JHC,0.0
4,4658151.0,dsgdb9nsd_000004,3.0,1.0,2JHC,0.0

## Build coupling dataframe: 
- num_coupling, coupling_dim, molecule_name, atom_index_0, atom_index_1, coupling_type, scalar_coupling, fc, sd, pso, dso, id

In [85]:
all_data = gd.concat([train, test])

In [86]:
coupling_frame = gd.merge(all_data, contribs, on=['molecule_name', 'atom_index_0', 'atom_index_1', 'type'], how='left')

In [87]:
count = coupling_frame.groupby('molecule_name').count().reset_index()[['molecule_name', 'id']]
count.columns = ['molecule_name', 'num_coupling']

In [88]:
coupling_frame = coupling_frame.merge(count, on='molecule_name', how='left')

In [89]:
coupling_frame['coupling_dim'] = 9

In [90]:
coupling_frame.head(10).to_pandas()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant,fc,sd,pso,dso,num_coupling,coupling_dim
0,37536.0,dsgdb9nsd_001714,13.0,2.0,3JHC,3.367970,3.668420,-0.050646,0.178090,-0.427896,45,9
1,37537.0,dsgdb9nsd_001714,13.0,4.0,1JHC,95.123901,94.165497,0.246794,-0.341500,1.053090,45,9
2,37538.0,dsgdb9nsd_001714,13.0,5.0,3JHC,4.398760,4.659280,-0.062925,-0.334714,0.137114,45,9
3,37539.0,dsgdb9nsd_001714,14.0,0.0,3JHC,1.473030,1.456240,-0.042350,-0.015625,0.074767,45,9
4,37540.0,dsgdb9nsd_001714,14.0,1.0,2JHC,27.999201,28.251301,0.026271,-0.316717,0.038375,45,9
5,37541.0,dsgdb9nsd_001714,14.0,2.0,3JHC,0.800390,0.806692,-0.024683,-0.020428,0.038810,45,9
6,37542.0,dsgdb9nsd_001714,14.0,4.0,3JHC,2.224980,2.325440,0.017551,0.279645,-0.397658,45,9
7,37543.0,dsgdb9nsd_001714,14.0,5.0,1JHC,106.818001,106.446999,0.302967,-1.070710,1.138660,45,9
8,37544.0,dsgdb9nsd_001715,7.0,1.0,2JHC,-1.605580,-1.716980,0.055339,0.255334,-0.199271,47,9
9,37545.0,dsgdb9nsd_001715,7.0,2.0,3JHC,1.823270,1.850450,0.049526,0.389146,-0.465847,47,9

In [82]:
coupling_frame.to_csv('/rapids/notebooks/srabhi/champs-2019/input/parquet/baseline_coupling_frame.csv', index=False)